//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cidade()
        {
            this.Conveniados = new HashSet<Conveniados>();
            this.RegistroObto = new HashSet<RegistroObto>();
        }
    
        public int Sequencia_cid { get; set; }
        public string Descricao_cid { get; set; }
        public int CodigoUf_unf { get; set; }
        public int CodigoIbge_ibg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conveniados> Conveniados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroObto> RegistroObto { get; set; }
        public virtual TabEstado TabEstado { get; set; }
        public virtual TabIbge TabIbge { get; set; }
    }
}
