//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conveniados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conveniados()
        {
            this.Dependentes = new HashSet<Dependentes>();
            this.Finaceiro = new HashSet<Finaceiro>();
            this.RegistroObto = new HashSet<RegistroObto>();
        }
    
        public int Sequencia_con { get; set; }
        public string Descricao_con { get; set; }
        public string Endereco_con { get; set; }
        public string Numero_con { get; set; }
        public string Bairro_con { get; set; }
        public int Sequencia_cid { get; set; }
        public System.DateTime DataNasc_con { get; set; }
        public Nullable<System.DateTime> DataObto_con { get; set; }
        public int Codigo_tco { get; set; }
        public bool Ativo_con { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dependentes> Dependentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finaceiro> Finaceiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroObto> RegistroObto { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
    }
}
