//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependentes
    {
        public int Sequencia_dep { get; set; }
        public int Sequencia_con { get; set; }
        public string Descricao_dep { get; set; }
        public Nullable<System.DateTime> DataObto_dep { get; set; }
        public System.DateTime DataNasc_dep { get; set; }
        public int Codigo_par { get; set; }
    
        public virtual Conveniados Conveniados { get; set; }
        public virtual TipoParentesco TipoParentesco { get; set; }
    }
}
