//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finaceiro
    {
        public int Sequencia_fin { get; set; }
        public int NumeroParcela_fin { get; set; }
        public int Sequencia_con { get; set; }
        public System.DateTime DataVencimento_fin { get; set; }
        public Nullable<System.DateTime> DataPagamento_fin { get; set; }
        public int ValorDebito_fin { get; set; }
        public Nullable<int> ValorPago_fin { get; set; }
    
        public virtual Conveniados Conveniados { get; set; }
    }
}
