//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroObto
    {
        public int Sequencia_obt { get; set; }
        public int Sequencia_con { get; set; }
        public System.DateTime DataObto_obt { get; set; }
        public string LocalObtio_obt { get; set; }
        public int Sequencia_cid { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Conveniados Conveniados { get; set; }
    }
}
