//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoContrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoContrato()
        {
            this.Conveniados = new HashSet<Conveniados>();
        }
    
        public int Codigo_tco { get; set; }
        public string Descricao_tco { get; set; }
        public int ValorContrato_tco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conveniados> Conveniados { get; set; }
    }
}
